#!/bin/sh

date=$(date +"%Y%m%d")

packages="extra-cmake-modules-git kde-solid-git hawaii-vibe-git hawaii-wallpapers-git hawaii-icon-themes-git hawaii-fluid-themes-git hawaii-fluid-git hawaii-greenisland-git hawaii-shell-git hawaii-shell-weston-plugins-git hawaii-system-preferences-git hawaii-terminal-git hawaii-archiver-git hawaii-eyesight-git sddm-qt5-git"

for pkg in $packages; do
	file=${pkg}-${date}-1-x86_64.pkg.tar.xz

	[ -f ~/chroot/root/repo/${file} ] && continue

	pushd $pkg

	echo "===> ${pkg}"

	[ ! -f ${file} ] && ../build

	if [ ! -f $file ]; then
		echo "$file doesn't exist!"
		exit 1
	fi

	cp $file ~/chroot/root/repo
	cd ~/chroot/root/repo
	repo-add hawaii.db.tar.gz $file

	popd
done
