#!/bin/sh

packages=(
          'hawaii-qt5-wayland-git'
          'hawaii-shell-git'
          'hawaii-meta-git'
          'hawaii-wallpapers-git'
          'hawaii-icon-themes-git'
          'hawaii-system-preferences-git'
          'greenisland-git'
)

for pkg in ${packages[@]}; do
	file=${pkg}*.pkg.tar.xz

	[ "${pkg}" = "hawaii-archiver-git" ] && continue
	[ "${pkg}" = "greenisland-git" ] && continue

	[ -f ~/chroot/root/repo/${file} ] && continue

	pushd $pkg

	echo "===> ${pkg}"

	[ ! -f ${file} ] && ../build

	if [ ! -f $file ]; then
		echo "$file doesn't exist!"
		exit 1
	fi

	cp $file ~/chroot/root/repo
	cd ~/chroot/root/repo
	repo-add hawaii.db.tar.gz $file

	popd
done
