#!/bin/bash

packages="qt5-base-git qt5-jsbackend-git qt5-xmlpatterns-git qt5-declarative-git qt5-quickcontrols-git qt5-svg-git qt5-imageformats-git qt5-graphicaleffects-git qt5-jsondb-git qt5-wayland-git qt5-multimedia-git qt5-connectivity-git qt5-3d-git qt5-location-git qt5-sensors-git qt5-webkit-git qt5-tools-git qt5-script-git qt5-quick1-git qtcreator-git polkit-qt5-git qt-accountsservice-addon-git"

for pkg in $packages; do
	file=${pkg}-*-x86_64.pkg.tar.xz

	[ -f ~/chroot/root/repo/${file} ] && continue

	pushd $pkg

	if [ $? -ne 0 ]; then
		exit $?
	fi

	echo "===> ${pkg}"

	[ ! -f ${file} ] && ../build

	if [ ! -f $file ]; then
		echo "$file doesn't exist!"
		exit 1
	fi

	cp $file ~/chroot/root/repo
	cd ~/chroot/root/repo
	repo-add hawaii.db.tar.gz $file

	popd
done
