#!/bin/bash

packages="qtbase-git qtjsbackend-git qtxmlpatterns-git qtdeclarative-git qtquickcontrols-git qtsvg-git qtimageformats-git qtgraphicaleffects-git qtwayland-git qtmultimedia-git qtwebkit-git qttools-git qtscript-git qtquick1-git qtcreator-git"

for pkg in $packages; do
	file=${pkg}-*-x86_64.pkg.tar.xz

	[ -f ~/chroot/root/repo/${file} ] && continue

	pushd $pkg

	if [ $? -ne 0 ]; then
		exit $?
	fi

	echo "===> ${pkg}"

	[ ! -f ${file} ] && ../build

	if [ ! -f $file ]; then
		echo "$file doesn't exist!"
		exit 1
	fi

	cp $file ~/chroot/root/repo
	cd ~/chroot/root/repo
	repo-add hawaii.db.tar.gz $file

	popd
done
