#!/bin/sh

packages="qtconfiguration-git qtaccountsservice-git
          hawaii-wallpapers-git hawaii-icon-themes-git
          hawaii-widget-styles-git fluid-git hawaii-greenisland-git
          hawaii-shell-git hawaii-system-preferences-git
          hawaii-terminal-git hawaii-archiver-git eyesight-git
          swordfish-git hawaii-meta-git
          qtconfiguration
          hawaii-wallpapers
          hawaii-widget-styles fluid
          hawaii-terminal eyesight"

srcpkgsdir=`readlink -f $(dirname $0)/srcpkgs`
rm -rf $srcpkgsdir
mkdir -p $srcpkgsdir

for pkg in $packages; do
	pushd $pkg

	echo "===> ${pkg}"

	makepkg --source -f
	rm -rf src
	mv *.src.tar.gz $srcpkgsdir

	popd
done
