#!/bin/sh

packages="kde-solid-git hawaii-vibe-git hawaii-wallpapers-git hawaii-icon-themes-git hawaii-fluid-git hawaii-greenisland-git hawaii-shell-git hawaii-shell-weston-plugins-git qtxdg-git hawaii-system-preferences-git hawaii-terminal-git hawaii-archiver-git hawaii-eyesight-git hawaii-swordfish-git hawaii-meta-git"

srcpkgsdir=`readlink -f $(dirname $0)/srcpkgs`
rm -rf $srcpkgsdir
mkdir -p $srcpkgsdir

for pkg in $packages; do
	pushd $pkg

	echo "===> ${pkg}"

	makepkg --source -f
	rm -rf src
	mv *.src.tar.gz $srcpkgsdir

	popd
done
